# PY_VER=3.9 CONDA_VER=4.10.3 HOST_UID=1000 docker-compose up --build
version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    build:
      context: .
      args:
        - CONDA_VER
        - PY_VER
    environment:
      - TWINE_USERNAME
      - TWINE_PASSWORD
    user: ${HOST_UID}:anaconda
    command:
      - sh
      - -c
      - |
        # Prepare for conda-forge
        grayskull pypi otumat
        # Package
        ./package.sh .
    volumes:
      - .:/main
      - ./pip_requirements_delivery.txt:/tmp/pip_requirements.txt
networks:
  main: