# PY_VER=3.9 CONDA_VER=4.10.3 AS_SCRIPT=FALSE docker-compose -f docker-compose-test.yml up --build --exit-code-from app
#
# Intended for running test suite locally.
# Note: If requirements or Dockerfile change, will need to add --build flag.
version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    extends:
      file: ./docker-compose.yml
      service: app
    environment:
      - AS_SCRIPT
    volumes:
      - ./pip_requirements_test.txt:/tmp/pip_requirements_test.txt
    command:
      - sh
      - -c
      - |
        set -e
        if echo "${AS_SCRIPT}" | grep -i true &>/dev/null; then
          pip install -r /tmp/pip_requirements_test.txt
          echo "------ SYNTAX TESTS ------"
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "------ UNIT TESTS ------"
          pytest # -sv --cov-report term-missing --cov=otumat /main/tests
          echo "------ STYLE TESTS ------"
          flake8 . --count --max-complexity=20 --max-line-length=95 --statistics
        else
          echo "=== Running ==="
          echo "Please see 'docker-compose-test.yaml' for detail on running tests."
          tail -f /dev/null
        fi
networks:
  main:
