# docker-compose up --build
version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    build:
      context: .
      args:
        ALPINE_VER: $ALPINE_VER
        PY_VER: $PY_VER
    environment:
      - TWINE_USERNAME
      - TWINE_PASSWORD
    working_dir: /src
    command:
      - sh
      - -c
      - |
        ./package.sh .
    volumes:
      - .:/src
networks:
  main: