# PY_VER=3.9 CONDA_VER=4.10.3 docker-compose up --build
version: '2.2'
x-net: &net
  networks:
      - main
services:
  # app:
  #   <<: *net
  #   build:
  #     context: .
  #     args:
  #       - ALPINE_VER
  #       - PY_VER
  #   environment:
  #     - TWINE_USERNAME
  #     - TWINE_PASSWORD
  #   working_dir: /src
  #   command:
  #     - sh
  #     - -c
  #     - |
  #       # Prepare for conda-forge
  #       grayskull pypi otumat
  #       # Package
  #       ./package.sh .
  #   volumes:
  #     - .:/src
  app:
    <<: *net
    build:
      context: .
      args:
        - PY_VER
        - CONDA_VER
    image: datajoint/otumat:v0.2.0
    # working_dir: /main
    command:
      - sh
      - -c
      - tail -f /dev/null
    volumes:
      - .:/main
networks:
  main: