version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    image: datajoint/pydev:${PY_VER}-alpine${ALPINE_VER}
    environment:
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=datajoint
      - DISPLAY
    working_dir: /src
    command: >
      /bin/sh -c
       "
        pip install --user nose nose-cov coveralls ptvsd twine .;
        ## You may run the below tests once sh'ed into container i.e. docker exec -it datajoint-python_app_1 sh
        # nosetests -vsw tests; #run all tests
        # nosetests -vs --tests=tests.test_external_class:test_insert_and_fetch; #run specific basic test
        # nosetests -vs --tests=tests.test_fetch:TestFetch.test_getattribute_for_fetch1; #run specific Class test
        ## Interactive Jupyter Notebook environment
        jupyter notebook &
        ## Remote debugger
        while true;
        do python -m ptvsd --host 0.0.0.0 --port 5678 --wait .;
        sleep 2;
        done;
       "
    ports:
      - "8888:8888"
      - "5678:5678"
    user: ${UID}:${GID}
    volumes:
      - .:/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mounted notebooks may go here
networks:
  main: