name: Development
on:
  # pull_request:
  push:
    branches:
      - 'watch_file'
    tags:
      - '*.*.*'
jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changelog entry
        id: changelog_reader
        uses: guzman-raphael/changelog-reader-action@v5
        with:
          path: ./CHANGELOG.md
      - name: Verify changelog parsing
        env:
          TAG_NAME: ${{steps.changelog_reader.outputs.version}}
          RELEASE_NAME: Release ${{steps.changelog_reader.outputs.version}}
          BODY: ${{steps.changelog_reader.outputs.changes}}
          PRERELEASE: ${{steps.changelog_reader.outputs.status == 'prereleased'}}
          DRAFT: ${{steps.changelog_reader.outputs.status == 'unreleased'}}
        run: |
          echo "TAG_NAME=${TAG_NAME}"
          echo "RELEASE_NAME=${RELEASE_NAME}"
          echo "BODY=${BODY}"
          echo "PRERELEASE=${PRERELEASE}"
          echo "DRAFT=${DRAFT}"
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - py_ver: 3.9
            conda_ver: 4.10.3
    env:
      PY_VER: ${{matrix.py_ver}}
      CONDA_VER: ${{matrix.conda_ver}}
      AS_SCRIPT: "TRUE"
    steps:
      - uses: actions/checkout@v2
      - name: Run primary tests
        run: |
          export HOST_UID=$(id -u)
          docker-compose -f docker-compose-test.yaml up --build --exit-code-from app